apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}-deployment
  labels:
    run: {{quote .Values.labels.AppName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    AppName: {{quote .Values.labels.AppName }}
    AppVersion: {{quote .Values.labels.AppVersion }}
spec:
  selector:
    matchLabels:
      run: {{quote .Values.labels.AppName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: {{quote .Values.labels.AppName }}
        AppName: {{quote .Values.labels.AppName }}
        container: app
    spec:
      containers:
        - name: {{quote .Values.labels.AppName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort:  {{ .Values.image.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path:  {{ .Values.readinessProbe.path }}
              port:  {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
