apiVersion: apps/v1
kind: Pod
metadata:
  name: k8s-bootcamp-pods-and-containers
spec:

  # Restart policy for the Pod's Containers
  restartPolicy: OnFailure

  # Pods have one or more Containers
  containers:

  - name: webserver
    image: nginx

  - name: shell
    image: busybox
    command: ['sh', '-c', 'echo "hello kube" && sleep 3600']