apiVersion: apps/v1
kind: Pod
metadata:
  name: pod-with-volume
spec:  
  restartPolicy: OnFailure

  volumes:
  - name: theSharedVolume
    emptyDir: {}

  containers:

  - name: webserver
    image: nginx
    volumeMounts:
    - name: theSharedVolume
      mountPath: /usr/share/nginx/html

  - name: shell
    image: centos
    command: ['sh', '-c', 'echo "<h1>hello world</h1>" > /opt/shared_volume/index.html && sleep 3600']
    volumeMounts:
    - name: theSharedVolume
      mountPath: /opt/shared_volume