apiVersion: v1
kind: Pod
metadata:
  name: pod-two-containers-no-volumes
spec:
  restartPolicy: OnFailure

  containers:

  - name: webserver
    image: nginx

  - name: shell
    image: centos
    command: ['sh', '-c', 'echo "hello kube" && sleep 3600']

